env:
  browser: true
  es2021: true
  node: true
parser: '@typescript-eslint/parser'
plugins:
  - 'svelte3'
  - '@typescript-eslint'
extends:
  - 'eslint:recommended'
globals:
  '__app': readonly
overrides:
  - files: ['*.svelte']
    processor: 'svelte3/svelte3'
  - files: ['*.ts, *.svelte']
    env:
      node: false
    extends:
      - 'plugin:@typescript-eslint/recommended'
    parserOptions:
      ecmaVersion: 12
      sourceType: module
      project:
        - './tsconfig.json'
      extraFileExtensions:
        - '.svelte'
rules:
  sort-imports:
    - error
    - ignoreCase: true
  '@typescript-eslint/no-unused-vars': ['error']
settings:
  svelte3/typescript': require('typescript')
